name: Deployment
on:
  workflow_dispatch:
    inputs:
      git-sha:
        description: The git SHA you want to deploy
        required: true
      environment:
        description: The environment you want to deplpoy to
        required: true
      target:
        description: The environment you want to deplpoy to
        required: true
        default: AWS

env:
  SERVICE: example-app
  US_REGISTRY_HOSTNAME: us.gcr.io
  NAMESPACE: vndly-${{ github.event.inputs.environment }}
  CLUSTER_NAME: vndly-cluster-${{ github.event.inputs.environment }}


jobs:
  deploy:
    name: Deploy a Version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-sha }}

      - name: Setup gcloud CLI
        if: ${{ github.event.inputs.target == 'GCP' }}
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets[format('{0}_GCP_CREDENTIALS', github.event.inputs.environment)] }}
          export_default_credentils: true
          project_id: ${{ secrets[format('{0}_GCP_PROJECT', github.event.inputs.environment)] }}
