name: Deployment
on:
  workflow_dispatch:
    inputs:
      git-sha:
        description: The git SHA you want to deploy
        required: true
      environment:
        description: The environment you want to deplpoy to
        required: true
      target:
        description: The environment you want to deplpoy to
        required: true
        default: AWS

env:
  SERVICE: example-app
  US_REGISTRY_HOSTNAME: us.gcr.io
  NAMESPACE: vndly-${{ github.event.inputs.environment }}
  CLUSTER_NAME: vndly-cluster-${{ github.event.inputs.environment }}


jobs:
  deploy:
    name: Deploy a Version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use the variable
        env:
          IMAGE_NAME: ${{ env.US_REGISTRY_HOSTNAME }}/my-project/${{ env.SERVICE }}:${{ github.event.inputs.git-sha }}
        run: echo deploying ${{ env.IMAGE_NAME }}

      - name: if statement
        if: ${{ github.event.inputs.environment == 'beta' && github.event.inputs.target == 'AWS' }}
        run: echo This is beta deployment to namespace ${{ env.NAMESPACE }} in cluster ${{ env.CLUSTER_NAME }}

      - name: Setup gcloud CLI
        if: ${{ github.event.inputs.target == 'GCP' }}
        uses: google-github-actions/setup-gcloud@master
        env:
          GCP_PROJECT: secrets.${{ github.event.inputs.environment }}_GCP_PROJECT
          GCP_CREDS: secrets.${{ github.event.inputs.environment }}_GCP_CREDENTIALS
        with:
          version: 'latest'
          service_account_key: ${{ env.GCP_CREDS }}
          export_default_credentils: true
          project_id: ${{ env.GCP_PROJECT }}
