name: Deployment
on:
  workflow_dispatch:
    inputs:
      git-sha:
        description: The git SHA you want to deploy
        required: True
      environment:
        description: The environment you want to deplpoy to
        required: True
env:
  SERVICE: example-app
  US_REGISTRY_HOSTNAME: us.gcr.io

jobs:
  deploy:
    name: Deploy a Version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use the variable
        env:
          IMAGE_NAME = ${{ env.US_REGISTRY_HOSTNAME }}/my-project/${{ env.SERVICE }}:${{ github.event.inputs.git-sha }}
        run: echo deploying ${{ env.IMAGE_NAME }}

      - name: if statement
        if: ${{ github.event.inputs.environment == 'beta' }}
        run: echo This is beta deployment
