name: On Push
on: [push]

env:
  IMAGE_BASE_NAME: this-is-it

jobs:
  build-and-push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and tag
        run: |
          echo "building adocker image"

      - name: get secrets
        run: |
          echo $HOME
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
          echo "Host github.com" > ~/.ssh/config
          echo "HostName github.com" >> ~/.ssh/config
          echo "IdentityFile ~/.ssh/github_actions" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh -T git@github.com
        shell: bash
