name: On Push
on: [push]

env:
  IMAGE_BASE_NAME: this-is-it

jobs:
  build-and-push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and tag
        run: |
          echo "building adocker image"

      - name: get secrets
        run: |

          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh -i /home/runner/.ssh/github_actions -T git@github.com
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
