name: On Push
on: [push]

env:
  IMAGE_BASE_NAME: this-is-it

jobs:
  build-and-push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and tag
        run: |
          echo "building adocker image"

      - name: get secrets
        run: |
          echo $SSH_KEY > key_id
          cat key_id
          chmod 600 ./key_id
          ssh -i ./key_id -T git@github.com
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
